### ISSUE TITLE
Flashカードを選択したらアプリが落ちる

### ISSUE THREAD

**Issue by cacaoMath** [cacaoMath/PLACE#32]
# 内容
1. ホーム画面>三点リーダー>config>Flach cardをオンにする
2. METADATAを保存してスタート
3. 以下のような部分でエラーとなりアプリが落ちる

```
I/FlashCardActivity: ttsの初期化に失敗しました．音声再生を中止します．
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.place, PID: 21418
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.place/com.example.place.activity.FlashCardActivity}: kotlin.UninitializedPropertyAccessException: lateinit property cardStackView has not been initialized
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property cardStackView has not been initialized
        at com.example.place.activity.FlashCardActivity.onInit(FlashCardActivity.kt:244)
        at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:862)
        at android.speech.tts.TextToSpeech.initTts(TextToSpeech.java:840)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:771)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:750)
        at android.speech.tts.TextToSpeech.<init>(TextToSpeech.java:734)
        at com.example.place.activity.FlashCardActivity.onCreate(FlashCardActivity.kt:76)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
I/m.example.plac: JIT allocated 59KB for compiled code of void com.example.place.Quiz.<init>()

```

**Comment by cacaoMath** [comment]
Pixel 6 API30のエミュレータだと落ちる
- TTSの問題かと思い設定を見たがエミュレータにはTTSの設定がなさそうだった

**Comment by cacaoMath** [comment]
実機Pixel4aだと問題なく動く

**Comment by cacaoMath** [comment]
実機では動く&エミュレータの問題そうなのでいったんバグではなく改善要件として`enhancement`にする

**Comment by cacaoMath** [comment]
ttsが初期化できない場合(tts = null)にnonnuullのlateint を使用しているため
エラーが出ているものと考えられる。そのため、
ttsはnullableなby lazyとする。
by lazyだと初期化後変更はくわえられないが、ttsは変わるようなものでないためよしとする。

**Comment by cacaoMath** [comment]
ttsではなく、cardstackViewの初期化が追い付いていないのdが原因みたいだった

**Comment by cacaoMath** [comment]
以下の初期化処理の前に、cardStackViewの初期化を入れる
```
tts = TextToSpeech(this,this)
```
